In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("강남구전세(3차전처리).csv")
df1

,Unnamed: 0,시군구,전월세구분,보증금(만원),건축년도,구분,전용면적(㎡),층,도로명주소,계약시작,계약종료,계약년월일,구,건축나이
0,0,서울특별시 강남구 개포동,전세,7500,1989,단독다가구,44.00,3.0,서울특별시 강남구 논현로4길,2022-06-01,2024-06-01,2022-06-01,강남구,34
1,1,서울특별시 강남구 개포동,전세,11000,1994,단독다가구,44.00,3.0,서울특별시 강남구 논현로10길,2022-05-01,2024-05-01,2022-05-20,강남구,29
2,2,서울특별시 강남구 개포동,전세,16800,2000,단독다가구,44.00,3.0,서울특별시 강남구 개포로20길,2022-02-01,2024-02-01,2022-01-22,강남구,23
3,3,서울특별시 강남구 개포동,전세,13000,1989,단독다가구,44.00,3.0,서울특별시 강남구 개포로15길,NaN,NaN,2022-02-18,강남구,34
4,4,서울특별시 강남구 개포동,전세,8000,1995,단독다가구,44.00,3.0,서울특별시 강남구 논현로6길,2022-07-01,2024-07-01,2022-06-25,강남구,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87356,87356,서울특별시 강남구 청담동,전세,10000,2003,오피스텔,17.73,3.0,서울특별시 강남구 학동로 437-6,NaN,NaN,2020-04-11,강남구,20
87357,87357,서울특별시 강남구 청담동,전세,10500,2003,오피스텔,17.73,1.0,서울특별시 강남구 학동로 437-6,NaN,NaN,2020-07-08,강남구,20
87358,87358,서울특별시 강남구 청담동,전세,11000,2003,오피스텔,17.73,1.0,서울특별시 강남구 학동로 437-6,NaN,NaN,2020-07-24,강남구,20
87359,87359,서울특별시 강남구 청담동,전세,13000,1991,오피스텔,22.77,11.0,서울특별시 강남구 도산대로 446,NaN,NaN,2020-09-25,강남구,32
87360,87360,서울특별시 강남구 청담동,전세,80000,2019,오피스텔,45.09,17.0,서울특별시 강남구 영동대로 740,NaN,NaN,2020-08-04,강남구,4

In [3]:
df1

,Unnamed: 0,시군구,전월세구분,보증금(만원),건축년도,구분,전용면적(㎡),층,도로명주소,계약시작,계약종료,계약년월일,구,건축나이
0,0,서울특별시 강남구 개포동,전세,7500,1989,단독다가구,44.00,3.0,서울특별시 강남구 논현로4길,2022-06-01,2024-06-01,2022-06-01,강남구,34
1,1,서울특별시 강남구 개포동,전세,11000,1994,단독다가구,44.00,3.0,서울특별시 강남구 논현로10길,2022-05-01,2024-05-01,2022-05-20,강남구,29
2,2,서울특별시 강남구 개포동,전세,16800,2000,단독다가구,44.00,3.0,서울특별시 강남구 개포로20길,2022-02-01,2024-02-01,2022-01-22,강남구,23
3,3,서울특별시 강남구 개포동,전세,13000,1989,단독다가구,44.00,3.0,서울특별시 강남구 개포로15길,NaN,NaN,2022-02-18,강남구,34
4,4,서울특별시 강남구 개포동,전세,8000,1995,단독다가구,44.00,3.0,서울특별시 강남구 논현로6길,2022-07-01,2024-07-01,2022-06-25,강남구,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87356,87356,서울특별시 강남구 청담동,전세,10000,2003,오피스텔,17.73,3.0,서울특별시 강남구 학동로 437-6,NaN,NaN,2020-04-11,강남구,20
87357,87357,서울특별시 강남구 청담동,전세,10500,2003,오피스텔,17.73,1.0,서울특별시 강남구 학동로 437-6,NaN,NaN,2020-07-08,강남구,20
87358,87358,서울특별시 강남구 청담동,전세,11000,2003,오피스텔,17.73,1.0,서울특별시 강남구 학동로 437-6,NaN,NaN,2020-07-24,강남구,20
87359,87359,서울특별시 강남구 청담동,전세,13000,1991,오피스텔,22.77,11.0,서울특별시 강남구 도산대로 446,NaN,NaN,2020-09-25,강남구,32
87360,87360,서울특별시 강남구 청담동,전세,80000,2019,오피스텔,45.09,17.0,서울특별시 강남구 영동대로 740,NaN,NaN,2020-08-04,강남구,4

In [4]:
df2 = pd.read_csv('경도위도값.csv')
df2.drop(columns = 'Unnamed: 0',  inplace = True)
df2

                     도로명주소   Latitude   Longitude
0          서울특별시 강남구 논현로4길  37.473722  127.052725
1         서울특별시 강남구 논현로10길  37.474587  127.049960
2         서울특별시 강남구 개포로20길  37.476862  127.048105
3         서울특별시 강남구 개포로15길  37.479661  127.045622
4          서울특별시 강남구 논현로6길  37.473422  127.051314
...                    ...        ...         ...
3724     서울특별시 강남구 역삼로 432  37.501439  127.054330
3725    서울특별시 강남구 압구정로 461  37.525283  127.047239
3726    서울특별시 강남구 도산대로 406  37.522821  127.039963
3727   서울특별시 강남구 논현로20길 12  37.478097  127.045854
3728  서울특별시 강남구 언주로 432-10  37.502156  127.044070

[3729 rows x 3 columns]

In [5]:
df1 = df1.merge(df2, how='left', on='도로명주소')
df1.drop(columns = 'Unnamed: 0',  inplace = True)
df1

,시군구,전월세구분,보증금(만원),건축년도,구분,전용면적(㎡),층,도로명주소,계약시작,계약종료,계약년월일,구,건축나이,Latitude,Longitude
0,서울특별시 강남구 개포동,전세,7500,1989,단독다가구,44.00,3.0,서울특별시 강남구 논현로4길,2022-06-01,2024-06-01,2022-06-01,강남구,34,37.473722,127.052725
1,서울특별시 강남구 개포동,전세,11000,1994,단독다가구,44.00,3.0,서울특별시 강남구 논현로10길,2022-05-01,2024-05-01,2022-05-20,강남구,29,37.474587,127.049960
2,서울특별시 강남구 개포동,전세,16800,2000,단독다가구,44.00,3.0,서울특별시 강남구 개포로20길,2022-02-01,2024-02-01,2022-01-22,강남구,23,37.476862,127.048105
3,서울특별시 강남구 개포동,전세,13000,1989,단독다가구,44.00,3.0,서울특별시 강남구 개포로15길,NaN,NaN,2022-02-18,강남구,34,37.479661,127.045622
4,서울특별시 강남구 개포동,전세,8000,1995,단독다가구,44.00,3.0,서울특별시 강남구 논현로6길,2022-07-01,2024-07-01,2022-06-25,강남구,28,37.473422,127.051314
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87356,서울특별시 강남구 청담동,전세,10000,2003,오피스텔,17.73,3.0,서울특별시 강남구 학동로 437-6,NaN,NaN,2020-04-11,강남구,20,37.519251,127.048902
87357,서울특별시 강남구 청담동,전세,10500,2003,오피스텔,17.73,1.0,서울특별시 강남구 학동로 437-6,NaN,NaN,2020-07-08,강남구,20,37.519251,127.048902
87358,서울특별시 강남구 청담동,전세,11000,2003,오피스텔,17.73,1.0,서울특별시 강남구 학동로 437-6,NaN,NaN,2020-07-24,강남구,20,37.519251,127.048902
87359,서울특별시 강남구 청담동,전세,13000,1991,오피스텔,22.77,11.0,서울특별시 강남구 도산대로 446,NaN,NaN,2020-09-25,강남구,32,37.523582,127.045128
87360,서울특별시 강남구 청담동,전세,80000,2019,오피스텔,45.09,17.0,서울특별시 강남구 영동대로 740,NaN,NaN,2020-08-04,강남구,4,37.524344,127.055328